[package]
name = "stepth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
disage = {path = "../disage"}
image = "0.23.0"
rayon = "*"
indicatif = "*"
