[package]
name = "stepth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
disage = {path = "./deps/disage"}
image = "0.23.0"
indicatif = "0.17.3"
rayon = "1.7.0"
